---

AWSTemplateFormatVersion: "2010-09-09"
Description: NetworkReadonlyRole with permissions boundary enforcing read-only visibility into network infrastructure

Resources:

  NetworkReadonlyBoundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: NetworkReadonlyBoundary
      Description: Permissions boundary preventing all write actions
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowReadOnlyAPIs
            Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:Get*
              - ec2:SearchTransitGatewayRoutes
              - vpc-lattice:Get*
              - vpc-lattice:List*
              - networkmanager:Get*
              - networkmanager:List*
              - directconnect:Describe*
              - elasticloadbalancing:Describe*
              - route53resolver:List*
              - route53resolver:Get*
              - logs:Describe*
              - logs:Get*
              - logs:FilterLogEvents
              - cloudwatch:Get*
              - cloudwatch:List*
              - cloudtrail:LookupEvents
              - config:Describe*
              - config:Get*
              - resource-explorer:*
              - resource-groups:*
              - tag:GetResources
              - tag:GetTagValues
              - ssm:Describe*
              - ssm:Get*
              - ssmmessages:*
              - ec2messages:*
              - iam:Get*
              - iam:List*
              - qbusiness:QueryAssistant
            Resource: "*"

          - Sid: DenyAllMutation
            Effect: Deny
            Action: "*"
            Resource: "*"
            Condition:
              StringLike:
                aws:RequestedRegion: "*"

  NetworkReadonlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: NetworkReadonlyPolicy
      Description: Role policy allowing read-only diagnostics and inventory access
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: NetworkInventory
            Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:Get*
              - ec2:SearchTransitGatewayRoutes
              - networkmanager:Get*
              - networkmanager:List*
              - directconnect:Describe*
              - elasticloadbalancing:Describe*
              - route53resolver:*
              - vpc-lattice:Get*
              - vpc-lattice:List*
            Resource: "*"

          - Sid: Observability
            Effect: Allow
            Action:
              - logs:Get*
              - logs:Describe*
              - logs:FilterLogEvents
              - cloudwatch:Get*
              - cloudwatch:List*
              - cloudtrail:LookupEvents
              - config:Get*
              - config:Describe*
            Resource: "*"

          - Sid: DiscoveryTools
            Effect: Allow
            Action:
              - resource-explorer:*
              - resource-groups:*
              - tag:GetResources
              - tag:GetTagValues
              - iam:Get*
              - iam:List*
              - ssm:Get*
              - ssm:Describe*
              - ssmmessages:*
              - ec2messages:*
              - qbusiness:QueryAssistant
            Resource: "*"

  NetworkReadonlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NetworkReadonlyRole
      Description: Human-assumed diagnostics role for read-only network visibility and inventory auditing
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowNetworkEngineers
            Effect: Allow
            Principal:
              AWS: "*"
            Action: sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      PermissionsBoundary: !Ref NetworkReadonlyBoundary
      ManagedPolicyArns:
        - !Ref NetworkReadonlyPolicy
      Tags:
        - Key: Purpose
          Value: NetworkReadonly
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Role
          Value: network-readonly
        - Key: Team
          Value: Network

Outputs:

  NetworkReadonlyRoleArn:
    Value: !GetAtt NetworkReadonlyRole.Arn
    Description: ARN of the IAM role for network diagnostics and inventory

  NetworkReadonlyPolicyArn:
    Value: !Ref NetworkReadonlyPolicy
    Description: ARN of the IAM policy used by the role

  NetworkReadonlyBoundaryArn:
    Value: !Ref NetworkReadonlyBoundary
    Description: ARN of the IAM permissions boundary attached to the role
