---

AWSTemplateFormatVersion: "2010-09-09"
Description: NetworkTelemetryRole for managing telemetry pipelines and observability integration

Resources:

  NetworkTelemetryBoundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: NetworkTelemetryBoundary
      Description: Permissions boundary enforcing telemetry-only operational access
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowTelemetryObservability
            Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - xray:*
              - config:Get*
              - config:BatchGet*
              - config:Describe*
              - ec2:Describe*
              - ec2:Get*
              - ec2:SearchTransitGatewayRoutes
              - networkmanager:Get*
              - networkmanager:Describe*
              - s3:PutObject
              - s3:GetObject
              - firehose:PutRecord
              - firehose:PutRecordBatch
              - kinesis:PutRecord
              - kinesis:PutRecords
              - sns:Publish
              - sqs:SendMessage
              - qbusiness:QueryAssistant
            Resource: "*"

          - Sid: DenyIAMMutation
            Effect: Deny
            Action:
              - iam:*
            Resource: "*"

  NetworkTelemetryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: NetworkTelemetryPolicy
      Description: Role policy for managing telemetry streams and observability pipelines
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: LogsAndMetrics
            Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - xray:*
            Resource: "*"

          - Sid: EC2NetworkRead
            Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:Get*
              - ec2:SearchTransitGatewayRoutes
              - networkmanager:Get*
              - networkmanager:Describe*
            Resource: "*"

          - Sid: StreamIngestion
            Effect: Allow
            Action:
              - firehose:PutRecord
              - firehose:PutRecordBatch
              - kinesis:PutRecord
              - kinesis:PutRecords
              - s3:PutObject
              - s3:GetObject
              - sns:Publish
              - sqs:SendMessage
            Resource: "*"

          - Sid: AmazonQ
            Effect: Allow
            Action: qbusiness:QueryAssistant
            Resource: "*"

  NetworkTelemetryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NetworkTelemetryRole
      Description: Role for telemetry services ingesting and routing observability data
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowServiceTelemetryAgents
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ec2.amazonaws.com
                - ecs-tasks.amazonaws.com
                - firehose.amazonaws.com
            Action: sts:AssumeRole
      PermissionsBoundary: !Ref NetworkTelemetryBoundary
      ManagedPolicyArns:
        - !Ref NetworkTelemetryPolicy
      Tags:
        - Key: Purpose
          Value: NetworkTelemetry
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Role
          Value: network-telemetry
        - Key: Team
          Value: Network

Outputs:

  NetworkTelemetryRoleArn:
    Value: !GetAtt NetworkTelemetryRole.Arn
    Description: ARN of the IAM role for telemetry services

  NetworkTelemetryPolicyArn:
    Value: !Ref NetworkTelemetryPolicy
    Description: ARN of the IAM policy used by the telemetry role

  NetworkTelemetryBoundaryArn:
    Value: !Ref NetworkTelemetryBoundary
    Description: ARN of the IAM permissions boundary attached to the telemetry role
